### ISSUE TITLE
裁剪不完全

### ISSUE THREAD

**Issue by SleepyFoxer** [liqvip/EasyView#2]
<img width="219" alt="裁剪问题" src="https://user-images.githubusercontent.com/13217225/148920409-c3b66b19-e06a-47d2-9deb-e2aa727e8f3e.png">

```xml
<com.github.easyview.EasyImageView
     android:layout_width="60dp"
     android:layout_height="60dp"
     android:scaleType="centerCrop"
     app:ev_radius="30dp"
     app:ev_stroke_color="#e6e6e6"
     app:ev_stroke_width="0.5dp" />
```

**Comment by liqvip** [comment]
你好，问题描述得不是很清楚！使用中如果遇到什么问题，请务必按照以下模板（步骤），将问题描述清楚，方便作者尽快的解决问题！
1. 在什么环境/情况下遇到了什么问题。
......
2. 如何重现该问题（描述具体重现步骤！可在此处贴截图和出现问题的代码片段）。
......
3. 你希望得到什么结果。
......

**Comment by liqvip** [comment]
> <img alt="裁剪问题" width="219" src="https://user-images.githubusercontent.com/13217225/148920409-c3b66b19-e06a-47d2-9deb-e2aa727e8f3e.png">
> 
> ```
> <com.github.easyview.EasyImageView
>      android:layout_width="60dp"
>      android:layout_height="60dp"
>      android:scaleType="centerCrop"
>      app:ev_radius="30dp"
>      app:ev_stroke_color="#e6e6e6"
>      app:ev_stroke_width="0.5dp" />
> ```

你好，问题描述得不是很清楚！使用中如果遇到什么问题，请务必按照以下模板（步骤），将问题描述清楚，方便作者尽快的解决问题！
1. 在什么环境/情况下遇到了什么问题。
......
2. 如何重现该问题（描述具体重现步骤！可在此处贴截图和出现问题的代码片段）。
......
3. 你希望得到什么结果。
......
